server:
  port: 8888

spring:
  application:
    name: rj-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/RichardJd/microservices-spring/
          default-label: main
          search-paths:
            - 'archives-config-server/greeting-service*'